---
swagger: '2.0'
info:
  version: 1.1.0
  description: "A Swagger definition for Auth0"
  title: "Auth0"
basePath: "/"
consumes:
- application/json
produces:
- application/json
host: OVERRIDE-ME-IN-CODE.auth0.com
schemes:
  - https
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
paths:
  "/userinfo":
    get:
      security:
        - Bearer: []
      description: Create a consumer
      responses:
        '200':
          description: Consumer was created
definitions:
  UserInfo:
    description: "Someone that interacts with the API"
    type: object
    properties:
      email_verified:
        type: boolean
        example: false
      email:
        type: string
        example: "test.account@userinfo.com"
      clientID:
        type: string
        example: "q2hnj2iu..."
      updated_at:
        type: string
        example: "2016-12-05T15:15:40.545Z"
      name:
        type: string
        example: "test.account@userinfo.com"
      picture:
        type: string
        example: "https://s.gravatar.com/avatar/dummy.png"
      user_id:
        type: string
        example: "auth0|58454..."
      nickname:
        type: string
        example: "test.account"
      created_at:
        type: string
        example: "2016-12-05T11:16:59.640Z"
      sub:
        type: string
        example: "auth0|58454..."
